packageExtensions:
  '@zeit/next-less@*':
    dependencies:
      'less': '*'
  'styled-components@*':
    dependencies:
      'react-is': '*'
  '@aws-amplify/backend-cli@*':
    dependencies:
      '@aws-sdk/types': '*'
